[package]
name = "clockwork"
version = "0.1.0"
authors = ["Layl <LaylConway@users.noreply.github.com>"]

[dependencies]
hyper = {git = "https://github.com/hyperium/hyper.git"}
log = "0.3.6"
num_cpus = "0.2.13"
route-recognizer = "0.1.11"
