[package]
name = "clockwork-handlebars"
version = "0.1.0"
authors = ["Layl <LaylConway@users.noreply.github.com>"]

[dependencies]
clockwork = {path = "../clockwork"}
webutil = {path = "../webutil"}
handlebars = "0.18.2"
rustc-serialize = "0.3.19"
